[phases.setup]
nixPkgs = ["...", "php81", "php81Extensions.mysqli", "php81Extensions.pdo", "php81Extensions.gd"]

[phases.build]
cmds = ["echo 'Build complete'"]

[start]
cmd = "php -S 0.0.0.0:$PORT -t unified/"