<?php
/**
 * lang.php - 다국어 지원 언어팩
 * 영어, 한국어, 일본어, 중국어, 몽골어, 베트남어, 태국어, 러시아어, 독일어, 스페인어
 */

if (session_status() === PHP_SESSION_NONE) {
    session_start();
}

// 지원 언어 목록
$supported_langs = ['en', 'ko', 'ja', 'zh', 'mn', 'vi', 'th', 'ru', 'de', 'es'];

// 언어 변경 요청 처리
if (isset($_GET['lang']) && in_array($_GET['lang'], $supported_langs)) {
    $_SESSION['rx_lang'] = $_GET['lang'];
    setcookie('rx_lang', $_GET['lang'], time() + (86400 * 30), "/");
    
    // 현재 URL에서 lang 파라미터 제거 후 리다이렉트
    $url = preg_replace('/([?&])lang=[^&]+(&|$)/', '$1', $_SERVER['REQUEST_URI']);
    $url = rtrim($url, '?&');
    header("Location: " . $url);
    exit;
}

// 현재 언어 결정 (기본값 en)
$current_lang = 'en';
if (isset($_SESSION['rx_lang'])) {
    $current_lang = $_SESSION['rx_lang'];
} elseif (isset($_COOKIE['rx_lang'])) {
    $current_lang = $_COOKIE['rx_lang'];
}

// 언어팩 데이터 배열 (10개국어 정밀 번역)
$lang_data = [
    'ko' => [
        'login_title' => '로그인', 'login_sub' => '대시보드에 접근하려면 로그인하세요.',
        'uid_label' => '아이디 (UID)', 'uid_ph' => 'UID를 입력하세요',
        'pwd_label' => '비밀번호', 'pwd_ph' => '비밀번호를 입력하세요',
        'btn_login' => '로그인', 'msg_enter_uid_pwd' => 'UID와 비밀번호를 입력해주세요.', 'login_fail' => 'UID 또는 비밀번호가 일치하지 않습니다.',
        'cp_title' => '비밀번호 변경', 'cp_sub' => '보안을 위해 비밀번호를 변경해 주세요.',
        'cp_uid' => '아이디', 'cp_exchange' => '거래소', 'cp_warn_init' => '초기 비밀번호를 사용 중입니다. 변경이 필요합니다.',
        'cp_curr_pwd' => '현재 비밀번호', 'cp_curr_ph' => '현재 비밀번호 입력',
        'cp_new_pwd' => '새 비밀번호', 'cp_new_ph' => '새 비밀번호 입력',
        'cp_conf_pwd' => '새 비밀번호 확인', 'cp_conf_ph' => '새 비밀번호 다시 입력',
        'cp_btn_change' => '비밀번호 변경하기', 'cp_back_dash' => '대시보드로 돌아가기',
        'cp_err_empty' => '모든 항목을 입력해주세요.', 'cp_err_curr' => '현재 비밀번호가 일치하지 않습니다.',
        'cp_err_len' => '새 비밀번호는 최소 4자 이상이어야 합니다.', 'cp_err_match' => '새 비밀번호가 일치하지 않습니다.', 'cp_err_same' => '현재 비밀번호와 달라야 합니다.',
        'cp_succ' => '성공적으로 변경되었습니다. 이동합니다...', 'cp_err_fail' => '변경 실패: ',
        'dash_title' => '대시보드', 'dash_chg_pwd' => '비밀번호 변경', 'dash_logout' => '로그아웃',
        'dash_admin_mode' => '관리자 모드', 'dash_member_list' => '회원 목록',
        'msg_update_ok' => '설정 저장 완료.', 'msg_txid_ok' => 'TXID 저장 완료.',
        'msg_trans_ok_amt' => '자산 이동 완료. 금액: ', 'msg_trans_fail_rsn' => '이동 실패: ', 'msg_db_error' => 'DB 오류: ',
        'lbl_sym' => '심볼', 'ph_sym' => '예: BTC-USDT', 'btn_search' => '검색',
        'tab_dash' => '대시보드', 'tab_cal' => '캘린더', 'tab_week' => '주간 수익', 'tab_history' => '자산 내역', 'tab_settings_api' => '설정',
        'err_data_load' => '데이터 로드 실패', 'err_data_load_desc' => 'API 설정을 확인하세요.', 'btn_retry' => '다시 시도', 'btn_debug_log' => '디버그',
        'lbl_today_pnl' => '오늘 손익', 'lbl_yest_pnl' => '어제 손익', 'lbl_30d_pnl' => '30일 손익', 'lbl_roi_vs' => '대비', 'lbl_total_pnl' => '누적 손익',
        'lbl_no_record' => '기록 없음', 'lbl_total_days_pre' => '총 ', 'lbl_total_days_post' => '일',
        'title_wallet' => '지갑 자산', 'lbl_fut_wallet' => '선물 지갑', 'lbl_base_amt' => '기준금', 'lbl_use_avail' => '사용가능',
        'lbl_spot_wallet' => '현물 지갑', 'lbl_reserve_rate' => '유보율', 'lbl_reserve_amt' => '유보금',
        'title_curr_pos' => '현재 포지션', 'th_symbol' => '심볼', 'th_position' => '포지션', 'th_leverage' => '레버리지',
        'th_init_qty' => '초기수량', 'th_entry_qty' => '진입수량', 'th_martin' => '마틴', 'lbl_times' => '회',
        'th_entry_px' => '진입가', 'th_curr_px' => '현재가', 'th_liq_px' => '청산가', 'th_unreal_pnl' => '미실현 손익',
        'lbl_refresh_5s' => '5초 갱신', 'th_roi' => '수익률', 'msg_no_pos' => '포지션 없음.',
        'title_hist_pos' => '과거 포지션', 'th_close_time' => '종료시간', 'th_close_px' => '종료가', 'th_real_pnl' => '실현 손익',
        'btn_prev' => '이전', 'btn_next' => '다음', 'msg_no_hist' => '내역 없음.',
        'title_cal' => '캘린더', 'btn_prev_mo' => '이전', 'cal_year' => '년 ', 'cal_month' => '월', 'btn_next_mo' => '다음', 'btn_go_today' => '오늘',
        'cal_sun' => '일', 'cal_mon' => '월', 'cal_tue' => '화', 'cal_wed' => '수', 'cal_thu' => '목', 'cal_fri' => '금', 'cal_sat' => '토',
        'cal_mon_tot' => '월 합계', 'cal_trade_days' => '거래일수', 'cal_days' => '일', 'cal_prof_loss' => '수익/손실',
        'title_week_roi' => '주간 수익률', 'title_txid_input' => 'TXID 입력', 'lbl_select_week' => '주차 선택', 'opt_select_week' => '선택...',
        'lbl_input_txid' => 'TXID', 'ph_txid' => 'TXID 입력', 'btn_save_txid' => '저장',
        'th_week_range' => '기간', 'th_week_pnl' => '주간 손익', 'th_avg_amt' => '평균 투자금', 'th_week_roi' => '주간 수익률', 'th_txid' => 'TXID', 'msg_no_data' => '데이터 없음.',
        'title_hist_amt' => '자산 변동 내역', 'th_chg_time' => '시간', 'th_type' => '구분', 'th_amt_before' => '변경 전', 'th_amt_after' => '변경 후',
        'badge_spot' => '현물', 'badge_fut' => '선물', 'msg_no_amt_hist' => '내역 없음.',
        'title_settings' => 'API 설정', 'lbl_api_key' => 'API Key', 'lbl_sec_key' => 'Secret Key', 'lbl_pwd' => '비밀번호',
        'lbl_reserve_set' => '유보율', 'lbl_res_0' => '0%', 'lbl_res_30' => '30%', 'lbl_res_100' => '100%', 'lbl_res_desc' => '급등락시 현물에서 선물로 이동할 비율',
        'lbl_fut_amt' => '선물 투자금', 'lbl_fut_amt_desc' => '봇 구동 기준 금액', 'lbl_spot_amt' => '현물 유보금',
        'confirm_save' => '저장하시겠습니까?', 'btn_save' => '저장',
        'title_transfer' => '자산 이동', 'confirm_transfer' => '이동하시겠습니까?', 'lbl_direction' => '방향',
        'opt_spot_to_fut' => '현물 -> 선물', 'opt_fut_to_spot' => '선물 -> 현물', 'lbl_transfer_amt' => '수량', 'ph_amt' => '수량', 'btn_transfer' => '실행',
        'lbl_refreshing' => '갱신 중...', 'lbl_sec_refresh' => '초', 'lbl_err_occurred' => '오류',
        'err_comm' => '통신 오류', 'err_amt_gt_zero' => '금액은 0보다 커야 합니다.', 'msg_trans_succ' => '전송 성공', 'msg_trans_fail' => '전송 실패',
        'err_spot_bal' => '현물 잔고 조회 실패', 'err_no_usdt_fut' => '선물 USDT 지갑이 없습니다.', 'err_fut_bal' => '선물 잔고 조회 실패', 'err_pos_fetch' => '포지션 조회 실패', 'err_hist_fetch' => '거래 내역 조회 실패',
        'err_no_api_key' => 'API 키가 설정되지 않았습니다.', 'err_api_keys_missing' => 'API 키 정보가 누락되었습니다.', 'err_fut_bal_fail' => '선물 잔고 오류', 'err_spot_bal_fail' => '현물 잔고 오류',
        'mdl_bal_title' => '자산 설정 확인',
        'mdl_bal_cancel' => '취소',
        'mdl_bal_confirm' => '확인',
        'mdl_bal_checking' => '거래소 자산 확인중...',
        'mdl_bal_fut' => '거래소 선물자산',
        'mdl_bal_spot' => '거래소 현물자산',
        'mdl_bal_set_amt' => '설정금액',
        'mdl_bal_warn_all' => '입력하신 설정금액이 선물과 현물 모두 실제 보유자산보다 많습니다.',
        'mdl_bal_warn_fut' => '입력하신 설정금액이 선물은 많고, 현물은 적습니다.',
        'mdl_bal_warn_spot' => '입력하신 설정금액이 현물은 많고, 선물은 적습니다.',
        'mdl_bal_warn_ask' => '이대로 세팅하시겠습니까?',
        'mdl_bal_info' => '보유 자산이 충분합니다. 입력하신 내용으로 세팅하시겠습니까?',
        'mdl_bal_err_api' => '실제 잔고를 확인할 수 없습니다. 입력한 금액으로 저장하시겠습니까?\n사유:',
        'mdl_bal_err_comm' => '통신 중 오류가 발생했습니다.',
        'mdl_bal_saving' => '저장 중...'
    ],
    'en' => [
        'login_title' => 'Login', 'login_sub' => 'Please login to access the dashboard.',
        'uid_label' => 'User ID (UID)', 'uid_ph' => 'Enter your UID',
        'pwd_label' => 'Password', 'pwd_ph' => 'Enter your password',
        'btn_login' => 'Login', 'msg_enter_uid_pwd' => 'Please enter UID and password.', 'login_fail' => 'Invalid UID or password.',
        'cp_title' => 'Change Password', 'cp_sub' => 'Please change your password for security.',
        'cp_uid' => 'UID', 'cp_exchange' => 'Exchange', 'cp_warn_init' => 'You are using the initial password. Please change it.',
        'cp_curr_pwd' => 'Current Password', 'cp_curr_ph' => 'Enter current password',
        'cp_new_pwd' => 'New Password', 'cp_new_ph' => 'Enter new password',
        'cp_conf_pwd' => 'Confirm Password', 'cp_conf_ph' => 'Re-enter new password',
        'cp_btn_change' => 'Change Password', 'cp_back_dash' => 'Back to Dashboard',
        'cp_err_empty' => 'Please fill in all fields.', 'cp_err_curr' => 'Current password does not match.',
        'cp_err_len' => 'New password must be at least 4 characters.', 'cp_err_match' => 'New passwords do not match.', 'cp_err_same' => 'New password must be different.',
        'cp_succ' => 'Successfully changed. Redirecting...', 'cp_err_fail' => 'Change failed: ',
        'dash_title' => 'Dashboard', 'dash_chg_pwd' => 'Change PWD', 'dash_logout' => 'Logout',
        'dash_admin_mode' => 'Admin Mode', 'dash_member_list' => 'Member List',
        'msg_update_ok' => 'Settings saved successfully.', 'msg_txid_ok' => 'TXID saved successfully.',
        'msg_trans_ok_amt' => 'Transfer complete. Amount: ', 'msg_trans_fail_rsn' => 'Transfer failed: ', 'msg_db_error' => 'DB error: ',
        'lbl_sym' => 'Symbol', 'ph_sym' => 'e.g., BTC-USDT', 'btn_search' => 'Search',
        'tab_dash' => 'Dashboard', 'tab_cal' => 'Calendar', 'tab_week' => 'Weekly ROI', 'tab_history' => 'Asset History', 'tab_settings_api' => 'Settings',
        'err_data_load' => 'Data Load Failed', 'err_data_load_desc' => 'Please check your API settings.', 'btn_retry' => 'Retry', 'btn_debug_log' => 'Debug',
        'lbl_today_pnl' => 'Today PnL', 'lbl_yest_pnl' => 'Yest PnL', 'lbl_30d_pnl' => '30d PnL', 'lbl_roi_vs' => 'vs', 'lbl_total_pnl' => 'Total PnL',
        'lbl_no_record' => 'No record', 'lbl_total_days_pre' => 'Total ', 'lbl_total_days_post' => ' Days',
        'title_wallet' => 'Wallet Assets', 'lbl_fut_wallet' => 'Futures Wallet', 'lbl_base_amt' => 'Base Amt', 'lbl_use_avail' => 'Available',
        'lbl_spot_wallet' => 'Spot Wallet', 'lbl_reserve_rate' => 'Reserve Rate', 'lbl_reserve_amt' => 'Reserve Amt',
        'title_curr_pos' => 'Current Positions', 'th_symbol' => 'Symbol', 'th_position' => 'Position', 'th_leverage' => 'Leverage',
        'th_init_qty' => 'Init Qty', 'th_entry_qty' => 'Entry Qty', 'th_martin' => 'Martin', 'lbl_times' => 'x',
        'th_entry_px' => 'Entry Px', 'th_curr_px' => 'Curr Px', 'th_liq_px' => 'Liq Px', 'th_unreal_pnl' => 'Unreal PnL',
        'lbl_refresh_5s' => '5s Refresh', 'th_roi' => 'ROI', 'msg_no_pos' => 'No open positions.',
        'title_hist_pos' => 'Position History', 'th_close_time' => 'Close Time', 'th_close_px' => 'Close Px', 'th_real_pnl' => 'Realized PnL',
        'btn_prev' => 'Prev', 'btn_next' => 'Next', 'msg_no_hist' => 'No history.',
        'title_cal' => 'Calendar', 'btn_prev_mo' => 'Prev', 'cal_year' => ' ', 'cal_month' => ' ', 'btn_next_mo' => 'Next', 'btn_go_today' => 'Today',
        'cal_sun' => 'Sun', 'cal_mon' => 'Mon', 'cal_tue' => 'Tue', 'cal_wed' => 'Wed', 'cal_thu' => 'Thu', 'cal_fri' => 'Fri', 'cal_sat' => 'Sat',
        'cal_mon_tot' => 'Month Total', 'cal_trade_days' => 'Trade Days', 'cal_days' => 'd', 'cal_prof_loss' => 'Win/Loss',
        'title_week_roi' => 'Weekly ROI', 'title_txid_input' => 'Input TXID', 'lbl_select_week' => 'Select Week', 'opt_select_week' => 'Select...',
        'lbl_input_txid' => 'TXID', 'ph_txid' => 'Enter TXID', 'btn_save_txid' => 'Save TXID',
        'th_week_range' => 'Period', 'th_week_pnl' => 'Weekly PnL', 'th_avg_amt' => 'Avg Capital', 'th_week_roi' => 'Weekly ROI', 'th_txid' => 'TXID', 'msg_no_data' => 'No data.',
        'title_hist_amt' => 'Asset Transfer History', 'th_chg_time' => 'Time', 'th_type' => 'Type', 'th_amt_before' => 'Before', 'th_amt_after' => 'After',
        'badge_spot' => 'Spot', 'badge_fut' => 'Futures', 'msg_no_amt_hist' => 'No history.',
        'title_settings' => 'API Settings', 'lbl_api_key' => 'API Key', 'lbl_sec_key' => 'Secret Key', 'lbl_pwd' => 'Password',
        'lbl_reserve_set' => 'Reserve Rate', 'lbl_res_0' => '0%', 'lbl_res_30' => '30%', 'lbl_res_100' => '100%', 'lbl_res_desc' => 'Ratio of profit moved to spot wallet',
        'lbl_fut_amt' => 'Futures Capital', 'lbl_fut_amt_desc' => 'Base amount for bot operation', 'lbl_spot_amt' => 'Spot Capital',
        'confirm_save' => 'Save changes?', 'btn_save' => 'Save',
        'title_transfer' => 'Asset Transfer', 'confirm_transfer' => 'Proceed with transfer?', 'lbl_direction' => 'Direction',
        'opt_spot_to_fut' => 'Spot -> Futures', 'opt_fut_to_spot' => 'Futures -> Spot', 'lbl_transfer_amt' => 'Amount', 'ph_amt' => 'Amount', 'btn_transfer' => 'Transfer',
        'lbl_refreshing' => 'Refreshing...', 'lbl_sec_refresh' => 's', 'lbl_err_occurred' => 'Error',
        'err_comm' => 'Comm error', 'err_amt_gt_zero' => 'Amount must be > 0.', 'msg_trans_succ' => 'Transfer Success', 'msg_trans_fail' => 'Transfer Failed',
        'err_spot_bal' => 'Spot balance fetch failed', 'err_no_usdt_fut' => 'No Futures USDT wallet', 'err_fut_bal' => 'Futures balance fetch failed', 'err_pos_fetch' => 'Position fetch failed', 'err_hist_fetch' => 'History fetch failed',
        'err_no_api_key' => 'API keys are not set.', 'err_api_keys_missing' => 'API key info is missing.', 'err_fut_bal_fail' => 'Futures Balance Error', 'err_spot_bal_fail' => 'Spot Balance Error',
        'mdl_bal_title' => 'Confirm Asset Settings',
        'mdl_bal_cancel' => 'Cancel',
        'mdl_bal_confirm' => 'Confirm',
        'mdl_bal_checking' => 'Checking exchange balance...',
        'mdl_bal_fut' => 'Exchange Futures Asset',
        'mdl_bal_spot' => 'Exchange Spot Asset',
        'mdl_bal_set_amt' => 'Setting Amount',
        'mdl_bal_warn_all' => 'The entered setting amounts for both futures and spot are greater than your actual balance.',
        'mdl_bal_warn_fut' => 'The entered futures amount is greater than your actual balance.',
        'mdl_bal_warn_spot' => 'The entered spot amount is greater than your actual balance.',
        'mdl_bal_warn_ask' => 'Do you want to proceed with these settings?',
        'mdl_bal_info' => 'Sufficient balance. Do you want to proceed with these settings?',
        'mdl_bal_err_api' => 'Could not verify actual balance. Save with the entered amounts?\nReason:',
        'mdl_bal_err_comm' => 'A communication error occurred.',
        'mdl_bal_saving' => 'Saving...'
    ],
    'ja' => [
        'login_title' => 'ログイン', 'login_sub' => 'ダッシュボードにアクセスするにはログインしてください。',
        'uid_label' => 'ユーザーID (UID)', 'uid_ph' => 'UIDを入力してください',
        'pwd_label' => 'パスワード', 'pwd_ph' => 'パスワードを入力してください',
        'btn_login' => 'ログイン', 'msg_enter_uid_pwd' => 'UIDとパスワードを入力してください。', 'login_fail' => 'UIDまたはパスワードが一致しません。',
        'cp_title' => 'パスワード変更', 'cp_sub' => 'セキュリティのためパスワードを変更してください。',
        'cp_uid' => 'UID', 'cp_exchange' => '取引所', 'cp_warn_init' => '初期パスワードを使用中です。変更が必要です。',
        'cp_curr_pwd' => '現在のパスワード', 'cp_curr_ph' => '現在のパスワードを入力',
        'cp_new_pwd' => '新しいパスワード', 'cp_new_ph' => '新しいパスワードを入力',
        'cp_conf_pwd' => '新しいパスワード(確認)', 'cp_conf_ph' => '新しいパスワードを再入力',
        'cp_btn_change' => 'パスワードを変更する', 'cp_back_dash' => 'ダッシュボードへ戻る',
        'cp_err_empty' => 'すべての項目を入力してください。', 'cp_err_curr' => '現在のパスワードが一致しません。',
        'cp_err_len' => '新しいパスワードは4文字以上で入力してください。', 'cp_err_match' => '新しいパスワードが一致しません。', 'cp_err_same' => '現在のパスワードとは異なるものを入力してください。',
        'cp_succ' => '正常に変更されました。移動します...', 'cp_err_fail' => '変更失敗: ',
        'dash_title' => 'ダッシュボード', 'dash_chg_pwd' => 'パスワード変更', 'dash_logout' => 'ログアウト',
        'dash_admin_mode' => '管理者モード', 'dash_member_list' => '会員リスト',
        'msg_update_ok' => '設定を保存しました。', 'msg_txid_ok' => 'TXIDを保存しました。',
        'msg_trans_ok_amt' => '資産の移動が完了しました。金額: ', 'msg_trans_fail_rsn' => '移動失敗: ', 'msg_db_error' => 'DBエラー: ',
        'lbl_sym' => 'シンボル', 'ph_sym' => '例: BTC-USDT', 'btn_search' => '検索',
        'tab_dash' => 'ダッシュボード', 'tab_cal' => 'カレンダー', 'tab_week' => '週間収益', 'tab_history' => '資産履歴', 'tab_settings_api' => '設定',
        'err_data_load' => 'データ読み込み失敗', 'err_data_load_desc' => 'API設定を確認してください。', 'btn_retry' => '再試行', 'btn_debug_log' => 'デバッグ',
        'lbl_today_pnl' => '本日の損益', 'lbl_yest_pnl' => '昨日の損益', 'lbl_30d_pnl' => '30日間の損益', 'lbl_roi_vs' => '対資本', 'lbl_total_pnl' => '累計損益',
        'lbl_no_record' => '記録なし', 'lbl_total_days_pre' => '合計 ', 'lbl_total_days_post' => ' 日',
        'title_wallet' => 'ウォレット資産', 'lbl_fut_wallet' => '先物ウォレット', 'lbl_base_amt' => '基準金', 'lbl_use_avail' => '利用可能',
        'lbl_spot_wallet' => '現物ウォレット', 'lbl_reserve_rate' => '留保率', 'lbl_reserve_amt' => '留保金',
        'title_curr_pos' => '現在のポジション', 'th_symbol' => 'シンボル', 'th_position' => 'ポジション', 'th_leverage' => 'レバレッジ',
        'th_init_qty' => '初期数量', 'th_entry_qty' => '参入数量', 'th_martin' => 'マーチン', 'lbl_times' => '回',
        'th_entry_px' => '参入価格', 'th_curr_px' => '現在価格', 'th_liq_px' => '清算価格', 'th_unreal_pnl' => '未実現損益',
        'lbl_refresh_5s' => '5秒更新', 'th_roi' => '収益率', 'msg_no_pos' => 'ポジションがありません。',
        'title_hist_pos' => '過去のポジション', 'th_close_time' => '終了時間', 'th_close_px' => '終了価格', 'th_real_pnl' => '実現損益',
        'btn_prev' => '前へ', 'btn_next' => '次へ', 'msg_no_hist' => '履歴がありません。',
        'title_cal' => 'カレンダー', 'btn_prev_mo' => '前月', 'cal_year' => '年 ', 'cal_month' => '月', 'btn_next_mo' => '次月', 'btn_go_today' => '今日',
        'cal_sun' => '日', 'cal_mon' => '月', 'cal_tue' => '火', 'cal_wed' => '水', 'cal_thu' => '木', 'cal_fri' => '金', 'cal_sat' => '土',
        'cal_mon_tot' => '月間合計', 'cal_trade_days' => '取引日数', 'cal_days' => '日', 'cal_prof_loss' => '利益/損失',
        'title_week_roi' => '週間収益率', 'title_txid_input' => 'TXID入力', 'lbl_select_week' => '週を選択', 'opt_select_week' => '選択...',
        'lbl_input_txid' => 'TXID', 'ph_txid' => 'TXIDを入力', 'btn_save_txid' => '保存',
        'th_week_range' => '期間', 'th_week_pnl' => '週間損益', 'th_avg_amt' => '平均投資額', 'th_week_roi' => '週間収益率', 'th_txid' => 'TXID', 'msg_no_data' => 'データがありません。',
        'title_hist_amt' => '資産変動履歴', 'th_chg_time' => '時間', 'th_type' => '区分', 'th_amt_before' => '変更前', 'th_amt_after' => '変更後',
        'badge_spot' => '現物', 'badge_fut' => '先物', 'msg_no_amt_hist' => '履歴がありません。',
        'title_settings' => 'API設定', 'lbl_api_key' => 'APIキー', 'lbl_sec_key' => 'シークレットキー', 'lbl_pwd' => 'パスワード',
        'lbl_reserve_set' => '留保率', 'lbl_res_0' => '0%', 'lbl_res_30' => '30%', 'lbl_res_100' => '100%', 'lbl_res_desc' => '収益発生時に現物ウォレットへ移動する割合',
        'lbl_fut_amt' => '先物投資額', 'lbl_fut_amt_desc' => 'ボット稼働の基準金額', 'lbl_spot_amt' => '現物留保金',
        'confirm_save' => '保存しますか？', 'btn_save' => '保存',
        'title_transfer' => '資産移動', 'confirm_transfer' => '移動を実行しますか？', 'lbl_direction' => '方向',
        'opt_spot_to_fut' => '現物 -> 先物', 'opt_fut_to_spot' => '先物 -> 現物', 'lbl_transfer_amt' => '数量', 'ph_amt' => '数量', 'btn_transfer' => '実行',
        'lbl_refreshing' => '更新中...', 'lbl_sec_refresh' => '秒', 'lbl_err_occurred' => 'エラー',
        'err_comm' => '通信エラー', 'err_amt_gt_zero' => '金額は0より大きくなければなりません。', 'msg_trans_succ' => '転送成功', 'msg_trans_fail' => '転送失敗',
        'err_spot_bal' => '現物残高の取得に失敗しました', 'err_no_usdt_fut' => '先物USDTウォレットがありません', 'err_fut_bal' => '先物残高の取得に失敗しました', 'err_pos_fetch' => 'ポジションの取得に失敗しました', 'err_hist_fetch' => '取引履歴の取得に失敗しました',
        'err_no_api_key' => 'APIキーが設定されていません。', 'err_api_keys_missing' => 'APIキー情報が不足しています。', 'err_fut_bal_fail' => '先物残高エラー', 'err_spot_bal_fail' => '現物残高エラー',
        'mdl_bal_title' => '資産設定の確認',
        'mdl_bal_cancel' => 'キャンセル',
        'mdl_bal_confirm' => '確認',
        'mdl_bal_checking' => '取引所の残高を確認中...',
        'mdl_bal_fut' => '取引所 先物資産',
        'mdl_bal_spot' => '取引所 現物資産',
        'mdl_bal_set_amt' => '設定金額',
        'mdl_bal_warn_all' => '入力された設定金額が、先物と現物の両方で実際の保有資産を上回っています。',
        'mdl_bal_warn_fut' => '入力された先物の設定金額が、実際の保有資産を上回っています。',
        'mdl_bal_warn_spot' => '入力された現物の設定金額が、実際の保有資産を上回っています。',
        'mdl_bal_warn_ask' => 'このまま設定しますか？',
        'mdl_bal_info' => '保有資産は十分です。入力した内容で設定しますか？',
        'mdl_bal_err_api' => '実際の残高を確認できませんでした。入力した金額で保存しますか？\n理由:',
        'mdl_bal_err_comm' => '通信中にエラーが発生しました。',
        'mdl_bal_saving' => '保存中...'
    ],
    'zh' => [
        'login_title' => '登录', 'login_sub' => '请登录以访问仪表板。',
        'uid_label' => '用户ID (UID)', 'uid_ph' => '请输入UID',
        'pwd_label' => '密码', 'pwd_ph' => '请输入密码',
        'btn_login' => '登录', 'msg_enter_uid_pwd' => '请输入UID和密码。', 'login_fail' => 'UID或密码不正确。',
        'cp_title' => '修改密码', 'cp_sub' => '为了安全，请修改您的密码。',
        'cp_uid' => '用户名', 'cp_exchange' => '交易所', 'cp_warn_init' => '您正在使用初始密码，请修改。',
        'cp_curr_pwd' => '当前密码', 'cp_curr_ph' => '输入当前密码',
        'cp_new_pwd' => '新密码', 'cp_new_ph' => '输入新密码',
        'cp_conf_pwd' => '确认新密码', 'cp_conf_ph' => '再次输入新密码',
        'cp_btn_change' => '确认修改', 'cp_back_dash' => '返回仪表板',
        'cp_err_empty' => '请填写所有字段。', 'cp_err_curr' => '当前密码不正确。',
        'cp_err_len' => '新密码至少需要4个字符。', 'cp_err_match' => '新密码不一致。', 'cp_err_same' => '新密码不能与当前密码相同。',
        'cp_succ' => '修改成功，正在跳转...', 'cp_err_fail' => '修改失败: ',
        'dash_title' => '仪表板', 'dash_chg_pwd' => '修改密码', 'dash_logout' => '退出登录',
        'dash_admin_mode' => '管理员模式', 'dash_member_list' => '会员列表',
        'msg_update_ok' => '设置保存成功。', 'msg_txid_ok' => 'TXID保存成功。',
        'msg_trans_ok_amt' => '资产划转成功。金额: ', 'msg_trans_fail_rsn' => '划转失败: ', 'msg_db_error' => '数据库错误: ',
        'lbl_sym' => '交易对', 'ph_sym' => '例: BTC-USDT', 'btn_search' => '搜索',
        'tab_dash' => '仪表板', 'tab_cal' => '日历', 'tab_week' => '每周收益', 'tab_history' => '资产记录', 'tab_settings_api' => '设置',
        'err_data_load' => '数据加载失败', 'err_data_load_desc' => '请检查API设置。', 'btn_retry' => '重试', 'btn_debug_log' => '调试日志',
        'lbl_today_pnl' => '今日盈亏', 'lbl_yest_pnl' => '昨日盈亏', 'lbl_30d_pnl' => '30日盈亏', 'lbl_roi_vs' => '收益率', 'lbl_total_pnl' => '累计盈亏',
        'lbl_no_record' => '暂无记录', 'lbl_total_days_pre' => '共 ', 'lbl_total_days_post' => ' 天',
        'title_wallet' => '钱包资产', 'lbl_fut_wallet' => '合约钱包', 'lbl_base_amt' => '基础本金', 'lbl_use_avail' => '可用余额',
        'lbl_spot_wallet' => '现货钱包', 'lbl_reserve_rate' => '预留率', 'lbl_reserve_amt' => '预留资金',
        'title_curr_pos' => '当前仓位', 'th_symbol' => '交易对', 'th_position' => '仓位', 'th_leverage' => '杠杆',
        'th_init_qty' => '初始数量', 'th_entry_qty' => '开仓数量', 'th_martin' => '马丁', 'lbl_times' => '次',
        'th_entry_px' => '开仓均价', 'th_curr_px' => '当前价格', 'th_liq_px' => '强平价格', 'th_unreal_pnl' => '未实现盈亏',
        'lbl_refresh_5s' => '5秒刷新', 'th_roi' => '回报率', 'msg_no_pos' => '暂无持仓。',
        'title_hist_pos' => '历史仓位', 'th_close_time' => '平仓时间', 'th_close_px' => '平仓价格', 'th_real_pnl' => '已实现盈亏',
        'btn_prev' => '上一页', 'btn_next' => '下一页', 'msg_no_hist' => '暂无历史记录。',
        'title_cal' => '收益日历', 'btn_prev_mo' => '上个月', 'cal_year' => '年 ', 'cal_month' => '月', 'btn_next_mo' => '下个月', 'btn_go_today' => '今天',
        'cal_sun' => '日', 'cal_mon' => '一', 'cal_tue' => '二', 'cal_wed' => '三', 'cal_thu' => '四', 'cal_fri' => '五', 'cal_sat' => '六',
        'cal_mon_tot' => '本月合计', 'cal_trade_days' => '交易天数', 'cal_days' => '天', 'cal_prof_loss' => '盈利/亏损',
        'title_week_roi' => '每周收益率', 'title_txid_input' => '输入TXID', 'lbl_select_week' => '选择周', 'opt_select_week' => '请选择...',
        'lbl_input_txid' => 'TXID', 'ph_txid' => '请输入TXID', 'btn_save_txid' => '保存TXID',
        'th_week_range' => '时间段', 'th_week_pnl' => '本周盈亏', 'th_avg_amt' => '平均本金', 'th_week_roi' => '本周收益率', 'th_txid' => 'TXID', 'msg_no_data' => '暂无数据。',
        'title_hist_amt' => '资金划转记录', 'th_chg_time' => '时间', 'th_type' => '类型', 'th_amt_before' => '划转前', 'th_amt_after' => '划转后',
        'badge_spot' => '现货', 'badge_fut' => '合约', 'msg_no_amt_hist' => '暂无记录。',
        'title_settings' => 'API设置', 'lbl_api_key' => 'API Key', 'lbl_sec_key' => 'Secret Key', 'lbl_pwd' => '资金密码',
        'lbl_reserve_set' => '预留比例', 'lbl_res_0' => '0%', 'lbl_res_30' => '30%', 'lbl_res_100' => '100%', 'lbl_res_desc' => '产生盈利时划转至现货钱包的比例',
        'lbl_fut_amt' => '合约本金', 'lbl_fut_amt_desc' => '机器人运行的基准金额', 'lbl_spot_amt' => '现货预留金',
        'confirm_save' => '确定要保存吗？', 'btn_save' => '保存',
        'title_transfer' => '资产划转', 'confirm_transfer' => '确定要划转吗？', 'lbl_direction' => '方向',
        'opt_spot_to_fut' => '现货 -> 合约', 'opt_fut_to_spot' => '合约 -> 现货', 'lbl_transfer_amt' => '数量', 'ph_amt' => '输入数量', 'btn_transfer' => '划转',
        'lbl_refreshing' => '刷新中...', 'lbl_sec_refresh' => '秒', 'lbl_err_occurred' => '出错了',
        'err_comm' => '网络通信错误', 'err_amt_gt_zero' => '金额必须大于0。', 'msg_trans_succ' => '划转成功', 'msg_trans_fail' => '划转失败',
        'err_spot_bal' => '获取现货余额失败', 'err_no_usdt_fut' => '没有合约USDT钱包', 'err_fut_bal' => '获取合约余额失败', 'err_pos_fetch' => '获取仓位失败', 'err_hist_fetch' => '获取历史记录失败',
        'err_no_api_key' => '未配置API密钥。', 'err_api_keys_missing' => 'API密钥信息缺失。', 'err_fut_bal_fail' => '合约余额错误', 'err_spot_bal_fail' => '现货余额错误',
        'mdl_bal_title' => '确认资产设置',
        'mdl_bal_cancel' => '取消',
        'mdl_bal_confirm' => '确认',
        'mdl_bal_checking' => '正在检查交易所余额...',
        'mdl_bal_fut' => '交易所合约资产',
        'mdl_bal_spot' => '交易所现货资产',
        'mdl_bal_set_amt' => '设置金额',
        'mdl_bal_warn_all' => '输入的合约和现货设置金额均大于实际持有资产。',
        'mdl_bal_warn_fut' => '输入的合约设置金额大于实际持有资产。',
        'mdl_bal_warn_spot' => '输入的现货设置金额大于实际持有资产。',
        'mdl_bal_warn_ask' => '是否按此设置继续？',
        'mdl_bal_info' => '资产充足。是否按输入的内容进行设置？',
        'mdl_bal_err_api' => '无法核实实际余额。是否以输入的金额保存？\n原因：',
        'mdl_bal_err_comm' => '通信过程中发生错误。',
        'mdl_bal_saving' => '保存中...'
    ],
    'mn' => [
        'login_title' => 'Нэвтрэх', 'login_sub' => 'Хянах самбарт нэвтрэхийн тулд нэвтэрнэ үү.',
        'uid_label' => 'Хэрэглэгчийн ID (UID)', 'uid_ph' => 'UID-ээ оруулна уу',
        'pwd_label' => 'Нууц үг', 'pwd_ph' => 'Нууц үгээ оруулна уу',
        'btn_login' => 'Нэвтрэх', 'msg_enter_uid_pwd' => 'UID болон нууц үгээ оруулна уу.', 'login_fail' => 'UID эсвэл нууц үг буруу байна.',
        'cp_title' => 'Нууц үг солих', 'cp_sub' => 'Аюулгүй байдлын үүднээс нууц үгээ солино уу.',
        'cp_uid' => 'UID', 'cp_exchange' => 'Бирж', 'cp_warn_init' => 'Та анхны нууц үгээ ашиглаж байна. Солино уу.',
        'cp_curr_pwd' => 'Одоогийн нууц үг', 'cp_curr_ph' => 'Одоогийн нууц үг',
        'cp_new_pwd' => 'Шинэ нууц үг', 'cp_new_ph' => 'Шинэ нууц үг',
        'cp_conf_pwd' => 'Шинэ нууц үг баталгаажуулах', 'cp_conf_ph' => 'Шинэ нууц үг дахин оруулах',
        'cp_btn_change' => 'Солих', 'cp_back_dash' => 'Буцах',
        'cp_err_empty' => 'Бүх талбарыг бөглөнө үү.', 'cp_err_curr' => 'Одоогийн нууц үг буруу байна.',
        'cp_err_len' => 'Шинэ нууц үг дор хаяж 4 тэмдэгттэй байх ёстой.', 'cp_err_match' => 'Нууц үгс таарахгүй байна.', 'cp_err_same' => 'Шинэ нууц үг өөр байх ёстой.',
        'cp_succ' => 'Амжилттай солигдлоо...', 'cp_err_fail' => 'Алдаа гарлаа: ',
        'dash_title' => 'Хянах самбар', 'dash_chg_pwd' => 'Нууц үг солих', 'dash_logout' => 'Гарах',
        'dash_admin_mode' => 'Админ горим', 'dash_member_list' => 'Гишүүд',
        'msg_update_ok' => 'Тохиргоо хадгалагдлаа.', 'msg_txid_ok' => 'TXID хадгалагдлаа.',
        'msg_trans_ok_amt' => 'Шилжүүлэг амжилттай. Дүн: ', 'msg_trans_fail_rsn' => 'Алдаа: ', 'msg_db_error' => 'Мэдээллийн сангийн алдаа: ',
        'lbl_sym' => 'Хос', 'ph_sym' => 'Ж: BTC-USDT', 'btn_search' => 'Хайх',
        'tab_dash' => 'Самбар', 'tab_cal' => 'Календарь', 'tab_week' => 'Долоо хоног', 'tab_history' => 'Түүх', 'tab_settings_api' => 'Тохиргоо',
        'err_data_load' => 'Мэдээлэл дуудахад алдаа гарлаа', 'err_data_load_desc' => 'API тохиргоогоо шалгана уу.', 'btn_retry' => 'Дахин оролдох', 'btn_debug_log' => 'Дебаг',
        'lbl_today_pnl' => 'Өнөөдрийн ашиг', 'lbl_yest_pnl' => 'Өчигдрийн ашиг', 'lbl_30d_pnl' => '30 хоногийн ашиг', 'lbl_roi_vs' => 'ROI', 'lbl_total_pnl' => 'Нийт ашиг',
        'lbl_no_record' => 'Мэдээлэл алга', 'lbl_total_days_pre' => 'Нийт ', 'lbl_total_days_post' => ' өдөр',
        'title_wallet' => 'Хэтэвч', 'lbl_fut_wallet' => 'Фьючерс хэтэвч', 'lbl_base_amt' => 'Үндсэн дүн', 'lbl_use_avail' => 'Боломжит',
        'lbl_spot_wallet' => 'Спот хэтэвч', 'lbl_reserve_rate' => 'Нөөцийн хувь', 'lbl_reserve_amt' => 'Нөөц дүн',
        'title_curr_pos' => 'Одоогийн позиц', 'th_symbol' => 'Хос', 'th_position' => 'Позиц', 'th_leverage' => 'Хөшүүрэг',
        'th_init_qty' => 'Эхний дүн', 'th_entry_qty' => 'Орсон дүн', 'th_martin' => 'Мартин', 'lbl_times' => 'удаа',
        'th_entry_px' => 'Орох үнэ', 'th_curr_px' => 'Одоогийн үнэ', 'th_liq_px' => 'Татан буугдах үнэ', 'th_unreal_pnl' => 'Хүлээгдэж буй ашиг',
        'lbl_refresh_5s' => '5с шинэчлэх', 'th_roi' => 'ROI', 'msg_no_pos' => 'Нээлттэй позиц алга.',
        'title_hist_pos' => 'Түүх', 'th_close_time' => 'Хаагдсан цаг', 'th_close_px' => 'Хаагдсан үнэ', 'th_real_pnl' => 'Бодит ашиг',
        'btn_prev' => 'Өмнөх', 'btn_next' => 'Дараах', 'msg_no_hist' => 'Түүх алга.',
        'title_cal' => 'Календарь', 'btn_prev_mo' => 'Өмнөх', 'cal_year' => ' ', 'cal_month' => ' сар', 'btn_next_mo' => 'Дараах', 'btn_go_today' => 'Өнөөдөр',
        'cal_sun' => 'Ня', 'cal_mon' => 'Да', 'cal_tue' => 'Мя', 'cal_wed' => 'Лх', 'cal_thu' => 'Пү', 'cal_fri' => 'Ба', 'cal_sat' => 'Бя',
        'cal_mon_tot' => 'Сар нийт', 'cal_trade_days' => 'Арилжааны өдөр', 'cal_days' => 'өдөр', 'cal_prof_loss' => 'Ашиг/Алдагдал',
        'title_week_roi' => 'Долоо хоногийн ROI', 'title_txid_input' => 'TXID оруулах', 'lbl_select_week' => 'Долоо хоног сонгох', 'opt_select_week' => 'Сонгох...',
        'lbl_input_txid' => 'TXID', 'ph_txid' => 'TXID оруулах', 'btn_save_txid' => 'Хадгалах',
        'th_week_range' => 'Хугацаа', 'th_week_pnl' => 'Ашиг', 'th_avg_amt' => 'Дундаж дүн', 'th_week_roi' => 'ROI', 'th_txid' => 'TXID', 'msg_no_data' => 'Мэдээлэл алга.',
        'title_hist_amt' => 'Шилжүүлгийн түүх', 'th_chg_time' => 'Цаг', 'th_type' => 'Төрөл', 'th_amt_before' => 'Өмнө нь', 'th_amt_after' => 'Дараа нь',
        'badge_spot' => 'Спот', 'badge_fut' => 'Фьючерс', 'msg_no_amt_hist' => 'Түүх алга.',
        'title_settings' => 'API тохиргоо', 'lbl_api_key' => 'API Key', 'lbl_sec_key' => 'Secret Key', 'lbl_pwd' => 'Нууц үг',
        'lbl_reserve_set' => 'Нөөцийн хувь', 'lbl_res_0' => '0%', 'lbl_res_30' => '30%', 'lbl_res_100' => '100%', 'lbl_res_desc' => 'Ашиг гарсан үед спот руу шилжүүлэх хувь',
        'lbl_fut_amt' => 'Фьючерс хөрөнгө', 'lbl_fut_amt_desc' => 'Бот ажиллах суурь дүн', 'lbl_spot_amt' => 'Спот нөөц',
        'confirm_save' => 'Хадгалах уу?', 'btn_save' => 'Хадгалах',
        'title_transfer' => 'Хөрөнгө шилжүүлэх', 'confirm_transfer' => 'Шилжүүлэх үү?', 'lbl_direction' => 'Чиглэл',
        'opt_spot_to_fut' => 'Спот -> Фьючерс', 'opt_fut_to_spot' => 'Фьючерс -> Спот', 'lbl_transfer_amt' => 'Дүн', 'ph_amt' => 'Дүн', 'btn_transfer' => 'Шилжүүлэх',
        'lbl_refreshing' => 'Шинэчилж байна...', 'lbl_sec_refresh' => 'с', 'lbl_err_occurred' => 'Алдаа',
        'err_comm' => 'Холболтын алдаа', 'err_amt_gt_zero' => 'Дүн 0-ээс их байх ёстой.', 'msg_trans_succ' => 'Амжилттай', 'msg_trans_fail' => 'Амжилтгүй',
        'err_spot_bal' => 'Спот үлдэгдэл дуудахад алдаа', 'err_no_usdt_fut' => 'Фьючерс USDT хэтэвч алга', 'err_fut_bal' => 'Фьючерс үлдэгдэл дуудахад алдаа', 'err_pos_fetch' => 'Позиц дуудахад алдаа', 'err_hist_fetch' => 'Түүх дуудахад алдаа',
        'err_no_api_key' => 'API тохируулаагүй байна.', 'err_api_keys_missing' => 'API мэдээлэл дутуу байна.', 'err_fut_bal_fail' => 'Фьючерс үлдэгдлийн алдаа', 'err_spot_bal_fail' => 'Спот үлдэгдлийн алдаа',
        'mdl_bal_title' => 'Хөрөнгийн тохиргоог баталгаажуулах',
        'mdl_bal_cancel' => 'Цуцлах',
        'mdl_bal_confirm' => 'Баталгаажуулах',
        'mdl_bal_checking' => 'Биржийн үлдэгдлийг шалгаж байна...',
        'mdl_bal_fut' => 'Биржийн фьючерс хөрөнгө',
        'mdl_bal_spot' => 'Биржийн спот хөрөнгө',
        'mdl_bal_set_amt' => 'Тохируулах дүн',
        'mdl_bal_warn_all' => 'Оруулсан фьючерс болон спотын тохиргооны дүн бодит үлдэгдлээс их байна.',
        'mdl_bal_warn_fut' => 'Оруулсан фьючерсийн тохиргооны дүн бодит үлдэгдлээс их байна.',
        'mdl_bal_warn_spot' => 'Оруулсан спотын тохиргооны дүн бодит үлдэгдлээс их байна.',
        'mdl_bal_warn_ask' => 'Энэ хэвээр нь тохируулах уу?',
        'mdl_bal_info' => 'Хөрөнгө хангалттай байна. Оруулсан мэдээллээр тохируулах уу?',
        'mdl_bal_err_api' => 'Бодит үлдэгдлийг шалгах боломжгүй байна. Оруулсан дүнгээр хадгалах уу?\nШалтгаан:',
        'mdl_bal_err_comm' => 'Холболтын алдаа гарлаа.',
        'mdl_bal_saving' => 'Хадгалж байна...'
    ],
    'vi' => [
        'login_title' => 'Đăng nhập', 'login_sub' => 'Vui lòng đăng nhập để truy cập bảng điều khiển.',
        'uid_label' => 'ID Người dùng (UID)', 'uid_ph' => 'Nhập UID của bạn',
        'pwd_label' => 'Mật khẩu', 'pwd_ph' => 'Nhập mật khẩu',
        'btn_login' => 'Đăng nhập', 'msg_enter_uid_pwd' => 'Vui lòng nhập UID và mật khẩu.', 'login_fail' => 'UID hoặc mật khẩu không hợp lệ.',
        'cp_title' => 'Đổi mật khẩu', 'cp_sub' => 'Vui lòng đổi mật khẩu để bảo mật.',
        'cp_uid' => 'UID', 'cp_exchange' => 'Sàn giao dịch', 'cp_warn_init' => 'Bạn đang sử dụng mật khẩu ban đầu. Vui lòng thay đổi.',
        'cp_curr_pwd' => 'Mật khẩu hiện tại', 'cp_curr_ph' => 'Nhập mật khẩu hiện tại',
        'cp_new_pwd' => 'Mật khẩu mới', 'cp_new_ph' => 'Nhập mật khẩu mới',
        'cp_conf_pwd' => 'Xác nhận mật khẩu mới', 'cp_conf_ph' => 'Nhập lại mật khẩu mới',
        'cp_btn_change' => 'Đổi mật khẩu', 'cp_back_dash' => 'Quay lại Bảng điều khiển',
        'cp_err_empty' => 'Vui lòng điền vào tất cả các trường.', 'cp_err_curr' => 'Mật khẩu hiện tại không khớp.',
        'cp_err_len' => 'Mật khẩu mới phải có ít nhất 4 ký tự.', 'cp_err_match' => 'Mật khẩu mới không khớp.', 'cp_err_same' => 'Mật khẩu mới phải khác mật khẩu hiện tại.',
        'cp_succ' => 'Đổi thành công. Đang chuyển hướng...', 'cp_err_fail' => 'Lỗi: ',
        'dash_title' => 'Bảng điều khiển', 'dash_chg_pwd' => 'Đổi MK', 'dash_logout' => 'Đăng xuất',
        'dash_admin_mode' => 'Chế độ Admin', 'dash_member_list' => 'Danh sách thành viên',
        'msg_update_ok' => 'Đã lưu cài đặt.', 'msg_txid_ok' => 'Đã lưu TXID.',
        'msg_trans_ok_amt' => 'Chuyển tiền thành công. Số tiền: ', 'msg_trans_fail_rsn' => 'Chuyển tiền thất bại: ', 'msg_db_error' => 'Lỗi DB: ',
        'lbl_sym' => 'Cặp giao dịch', 'ph_sym' => 'VD: BTC-USDT', 'btn_search' => 'Tìm kiếm',
        'tab_dash' => 'Bảng điều khiển', 'tab_cal' => 'Lịch', 'tab_week' => 'Lợi nhuận tuần', 'tab_history' => 'Lịch sử tài sản', 'tab_settings_api' => 'Cài đặt',
        'err_data_load' => 'Lỗi tải dữ liệu', 'err_data_load_desc' => 'Vui lòng kiểm tra cài đặt API.', 'btn_retry' => 'Thử lại', 'btn_debug_log' => 'Gỡ lỗi',
        'lbl_today_pnl' => 'PnL Hôm nay', 'lbl_yest_pnl' => 'PnL Hôm qua', 'lbl_30d_pnl' => 'PnL 30 ngày', 'lbl_roi_vs' => 'Tỷ suất', 'lbl_total_pnl' => 'Tổng PnL',
        'lbl_no_record' => 'Không có hồ sơ', 'lbl_total_days_pre' => 'Tổng ', 'lbl_total_days_post' => ' ngày',
        'title_wallet' => 'Tài sản Ví', 'lbl_fut_wallet' => 'Ví Futures', 'lbl_base_amt' => 'Vốn cơ sở', 'lbl_use_avail' => 'Khả dụng',
        'lbl_spot_wallet' => 'Ví Spot', 'lbl_reserve_rate' => 'Tỷ lệ dự trữ', 'lbl_reserve_amt' => 'Tiền dự trữ',
        'title_curr_pos' => 'Vị thế hiện tại', 'th_symbol' => 'Cặp', 'th_position' => 'Vị thế', 'th_leverage' => 'Đòn bẩy',
        'th_init_qty' => 'SL ban đầu', 'th_entry_qty' => 'SL vào lệnh', 'th_martin' => 'Martin', 'lbl_times' => 'lần',
        'th_entry_px' => 'Giá vào lệnh', 'th_curr_px' => 'Giá hiện tại', 'th_liq_px' => 'Giá thanh lý', 'th_unreal_pnl' => 'PnL chưa thực hiện',
        'lbl_refresh_5s' => 'Làm mới 5s', 'th_roi' => 'ROI', 'msg_no_pos' => 'Không có vị thế mở.',
        'title_hist_pos' => 'Lịch sử vị thế', 'th_close_time' => 'Thời gian đóng', 'th_close_px' => 'Giá đóng', 'th_real_pnl' => 'PnL đã thực hiện',
        'btn_prev' => 'Trang trước', 'btn_next' => 'Trang sau', 'msg_no_hist' => 'Không có lịch sử.',
        'title_cal' => 'Lịch', 'btn_prev_mo' => 'Tháng trước', 'cal_year' => ' ', 'cal_month' => ' ', 'btn_next_mo' => 'Tháng sau', 'btn_go_today' => 'Hôm nay',
        'cal_sun' => 'CN', 'cal_mon' => 'T2', 'cal_tue' => 'T3', 'cal_wed' => 'T4', 'cal_thu' => 'T5', 'cal_fri' => 'T6', 'cal_sat' => 'T7',
        'cal_mon_tot' => 'Tổng tháng', 'cal_trade_days' => 'Ngày giao dịch', 'cal_days' => 'ngày', 'cal_prof_loss' => 'Thắng/Thua',
        'title_week_roi' => 'ROI hàng tuần', 'title_txid_input' => 'Nhập TXID', 'lbl_select_week' => 'Chọn Tuần', 'opt_select_week' => 'Chọn...',
        'lbl_input_txid' => 'TXID', 'ph_txid' => 'Nhập TXID', 'btn_save_txid' => 'Lưu TXID',
        'th_week_range' => 'Giai đoạn', 'th_week_pnl' => 'PnL Tuần', 'th_avg_amt' => 'Vốn trung bình', 'th_week_roi' => 'ROI Tuần', 'th_txid' => 'TXID', 'msg_no_data' => 'Không có dữ liệu.',
        'title_hist_amt' => 'Lịch sử chuyển tiền', 'th_chg_time' => 'Thời gian', 'th_type' => 'Loại', 'th_amt_before' => 'Trước', 'th_amt_after' => 'Sau',
        'badge_spot' => 'Spot', 'badge_fut' => 'Futures', 'msg_no_amt_hist' => 'Không có lịch sử.',
        'title_settings' => 'Cài đặt API', 'lbl_api_key' => 'API Key', 'lbl_sec_key' => 'Secret Key', 'lbl_pwd' => 'Mật khẩu',
        'lbl_reserve_set' => 'Tỷ lệ dự trữ', 'lbl_res_0' => '0%', 'lbl_res_30' => '30%', 'lbl_res_100' => '100%', 'lbl_res_desc' => 'Tỷ lệ lợi nhuận chuyển sang ví Spot',
        'lbl_fut_amt' => 'Vốn Futures', 'lbl_fut_amt_desc' => 'Số tiền cơ sở để bot hoạt động', 'lbl_spot_amt' => 'Vốn Spot',
        'confirm_save' => 'Bạn có chắc muốn lưu?', 'btn_save' => 'Lưu',
        'title_transfer' => 'Chuyển tài sản', 'confirm_transfer' => 'Xác nhận chuyển?', 'lbl_direction' => 'Hướng',
        'opt_spot_to_fut' => 'Spot -> Futures', 'opt_fut_to_spot' => 'Futures -> Spot', 'lbl_transfer_amt' => 'Số lượng', 'ph_amt' => 'Nhập số lượng', 'btn_transfer' => 'Chuyển',
        'lbl_refreshing' => 'Đang làm mới...', 'lbl_sec_refresh' => 's', 'lbl_err_occurred' => 'Lỗi',
        'err_comm' => 'Lỗi mạng', 'err_amt_gt_zero' => 'Số tiền phải > 0.', 'msg_trans_succ' => 'Thành công', 'msg_trans_fail' => 'Thất bại',
        'err_spot_bal' => 'Lỗi số dư Spot', 'err_no_usdt_fut' => 'Không có ví USDT', 'err_fut_bal' => 'Lỗi số dư Futures', 'err_pos_fetch' => 'Lỗi lấy vị thế', 'err_hist_fetch' => 'Lỗi lấy lịch sử',
        'err_no_api_key' => 'API Key chưa được thiết lập.', 'err_api_keys_missing' => 'Thiếu thông tin API Key.', 'err_fut_bal_fail' => 'Lỗi số dư Futures', 'err_spot_bal_fail' => 'Lỗi số dư Spot',
        'mdl_bal_title' => 'Xác nhận Cài đặt Tài sản',
        'mdl_bal_cancel' => 'Hủy',
        'mdl_bal_confirm' => 'Xác nhận',
        'mdl_bal_checking' => 'Đang kiểm tra số dư sàn...',
        'mdl_bal_fut' => 'Tài sản Futures trên Sàn',
        'mdl_bal_spot' => 'Tài sản Spot trên Sàn',
        'mdl_bal_set_amt' => 'Số tiền Cài đặt',
        'mdl_bal_warn_all' => 'Số tiền cài đặt cho cả futures và spot lớn hơn số dư thực tế của bạn.',
        'mdl_bal_warn_fut' => 'Số tiền cài đặt cho futures lớn hơn số dư thực tế của bạn.',
        'mdl_bal_warn_spot' => 'Số tiền cài đặt cho spot lớn hơn số dư thực tế của bạn.',
        'mdl_bal_warn_ask' => 'Bạn có muốn tiếp tục với các cài đặt này không?',
        'mdl_bal_info' => 'Số dư đủ. Bạn có muốn tiếp tục thiết lập không?',
        'mdl_bal_err_api' => 'Không thể xác minh số dư thực tế. Lưu với số tiền đã nhập?\nLý do:',
        'mdl_bal_err_comm' => 'Đã xảy ra lỗi giao tiếp.',
        'mdl_bal_saving' => 'Đang lưu...'
    ],
    'th' => [
        'login_title' => 'เข้าสู่ระบบ', 'login_sub' => 'กรุณาเข้าสู่ระบบเพื่อใช้งานแดชบอร์ด',
        'uid_label' => 'ผู้ใช้ (UID)', 'uid_ph' => 'ใส่ UID ของคุณ',
        'pwd_label' => 'รหัสผ่าน', 'pwd_ph' => 'ใส่รหัสผ่าน',
        'btn_login' => 'เข้าสู่ระบบ', 'msg_enter_uid_pwd' => 'กรุณาใส่ UID และรหัสผ่าน', 'login_fail' => 'UID หรือรหัสผ่านไม่ถูกต้อง',
        'cp_title' => 'เปลี่ยนรหัสผ่าน', 'cp_sub' => 'เพื่อความปลอดภัย กรุณาเปลี่ยนรหัสผ่านของคุณ',
        'cp_uid' => 'UID', 'cp_exchange' => 'ตลาดซื้อขาย', 'cp_warn_init' => 'คุณกำลังใช้รหัสผ่านเริ่มต้น กรุณาเปลี่ยนใหม่',
        'cp_curr_pwd' => 'รหัสผ่านปัจจุบัน', 'cp_curr_ph' => 'ใส่รหัสผ่านปัจจุบัน',
        'cp_new_pwd' => 'รหัสผ่านใหม่', 'cp_new_ph' => 'ใส่รหัสผ่านใหม่',
        'cp_conf_pwd' => 'ยืนยันรหัสผ่านใหม่', 'cp_conf_ph' => 'ใส่รหัสผ่านใหม่อีกครั้ง',
        'cp_btn_change' => 'เปลี่ยนรหัสผ่าน', 'cp_back_dash' => 'กลับสู่แดชบอร์ด',
        'cp_err_empty' => 'กรุณากรอกข้อมูลให้ครบถ้วน', 'cp_err_curr' => 'รหัสผ่านปัจจุบันไม่ถูกต้อง',
        'cp_err_len' => 'รหัสผ่านใหม่ต้องมีอย่างน้อย 4 ตัวอักษร', 'cp_err_match' => 'รหัสผ่านใหม่ไม่ตรงกัน', 'cp_err_same' => 'รหัสผ่านใหม่ต้องไม่ซ้ำกับของเดิม',
        'cp_succ' => 'เปลี่ยนรหัสผ่านสำเร็จ กำลังไปหน้าถัดไป...', 'cp_err_fail' => 'เปลี่ยนไม่สำเร็จ: ',
        'dash_title' => 'แดชบอร์ด', 'dash_chg_pwd' => 'เปลี่ยนรหัสผ่าน', 'dash_logout' => 'ออกจากระบบ',
        'dash_admin_mode' => 'โหมดผู้ดูแล', 'dash_member_list' => 'รายชื่อสมาชิก',
        'msg_update_ok' => 'บันทึกการตั้งค่าแล้ว', 'msg_txid_ok' => 'บันทึก TXID แล้ว',
        'msg_trans_ok_amt' => 'โอนสำเร็จ จำนวน: ', 'msg_trans_fail_rsn' => 'โอนไม่สำเร็จ: ', 'msg_db_error' => 'ข้อผิดพลาด DB: ',
        'lbl_sym' => 'คู่เหรียญ', 'ph_sym' => 'เช่น BTC-USDT', 'btn_search' => 'ค้นหา',
        'tab_dash' => 'แดชบอร์ด', 'tab_cal' => 'ปฏิทิน', 'tab_week' => 'รายได้สัปดาห์', 'tab_history' => 'ประวัติสินทรัพย์', 'tab_settings_api' => 'ตั้งค่า',
        'err_data_load' => 'โหลดข้อมูลไม่สำเร็จ', 'err_data_load_desc' => 'โปรดตรวจสอบการตั้งค่า API', 'btn_retry' => 'ลองใหม่', 'btn_debug_log' => 'แก้บั๊ก',
        'lbl_today_pnl' => 'กำไร/ขาดทุน วันนี้', 'lbl_yest_pnl' => 'กำไร/ขาดทุน เมื่อวาน', 'lbl_30d_pnl' => 'กำไร 30 วัน', 'lbl_roi_vs' => 'ROI', 'lbl_total_pnl' => 'กำไรรวม',
        'lbl_no_record' => 'ไม่มีข้อมูล', 'lbl_total_days_pre' => 'รวม ', 'lbl_total_days_post' => ' วัน',
        'title_wallet' => 'กระเป๋าเงิน', 'lbl_fut_wallet' => 'กระเป๋า Futures', 'lbl_base_amt' => 'ทุนเริ่มต้น', 'lbl_use_avail' => 'ใช้ได้',
        'lbl_spot_wallet' => 'กระเป๋า Spot', 'lbl_reserve_rate' => 'อัตราสำรอง', 'lbl_reserve_amt' => 'ยอดสำรอง',
        'title_curr_pos' => 'โพสิชันปัจจุบัน', 'th_symbol' => 'คู่เหรียญ', 'th_position' => 'โพสิชัน', 'th_leverage' => 'เลเวอเรจ',
        'th_init_qty' => 'จำนวนแรก', 'th_entry_qty' => 'จำนวนจริง', 'th_martin' => 'มาร์ติน', 'lbl_times' => 'ครั้ง',
        'th_entry_px' => 'ราคาเข้า', 'th_curr_px' => 'ราคาปัจจุบัน', 'th_liq_px' => 'ราคาชำระ', 'th_unreal_pnl' => 'กำไรยังไม่รับรู้',
        'lbl_refresh_5s' => 'รีเฟรช 5 วินาที', 'th_roi' => 'ROI', 'msg_no_pos' => 'ไม่มีโพสิชันเปิด',
        'title_hist_pos' => 'ประวัติโพสิชัน', 'th_close_time' => 'เวลาปิด', 'th_close_px' => 'ราคาปิด', 'th_real_pnl' => 'กำไรรับรู้',
        'btn_prev' => 'ก่อนหน้า', 'btn_next' => 'ถัดไป', 'msg_no_hist' => 'ไม่มีประวัติ',
        'title_cal' => 'ปฏิทิน', 'btn_prev_mo' => 'เดือนก่อน', 'cal_year' => ' ', 'cal_month' => ' ', 'btn_next_mo' => 'เดือนหน้า', 'btn_go_today' => 'วันนี้',
        'cal_sun' => 'อา', 'cal_mon' => 'จ', 'cal_tue' => 'อ', 'cal_wed' => 'พ', 'cal_thu' => 'พฤ', 'cal_fri' => 'ศ', 'cal_sat' => 'ส',
        'cal_mon_tot' => 'รวมเดือนนี้', 'cal_trade_days' => 'วันซื้อขาย', 'cal_days' => 'วัน', 'cal_prof_loss' => 'กำไร/ขาดทุน',
        'title_week_roi' => 'ROI รายสัปดาห์', 'title_txid_input' => 'ใส่ TXID', 'lbl_select_week' => 'เลือกสัปดาห์', 'opt_select_week' => 'เลือก...',
        'lbl_input_txid' => 'TXID', 'ph_txid' => 'ใส่ TXID', 'btn_save_txid' => 'บันทึก TXID',
        'th_week_range' => 'ช่วงเวลา', 'th_week_pnl' => 'กำไรสัปดาห์', 'th_avg_amt' => 'ทุนเฉลี่ย', 'th_week_roi' => 'ROI สัปดาห์', 'th_txid' => 'TXID', 'msg_no_data' => 'ไม่มีข้อมูล',
        'title_hist_amt' => 'ประวัติโอนเงิน', 'th_chg_time' => 'เวลา', 'th_type' => 'ประเภท', 'th_amt_before' => 'ก่อน', 'th_amt_after' => 'หลัง',
        'badge_spot' => 'Spot', 'badge_fut' => 'Futures', 'msg_no_amt_hist' => 'ไม่มีประวัติ',
        'title_settings' => 'ตั้งค่า API', 'lbl_api_key' => 'API Key', 'lbl_sec_key' => 'Secret Key', 'lbl_pwd' => 'รหัสผ่าน',
        'lbl_reserve_set' => 'สัดส่วนสำรอง', 'lbl_res_0' => '0%', 'lbl_res_30' => '30%', 'lbl_res_100' => '100%', 'lbl_res_desc' => 'เปอร์เซ็นต์กำไรที่โอนเข้ากระเป๋า Spot',
        'lbl_fut_amt' => 'ทุน Futures', 'lbl_fut_amt_desc' => 'เงินทุนฐานสำหรับรันบอท', 'lbl_spot_amt' => 'ทุน Spot',
        'confirm_save' => 'ยืนยันการบันทึก?', 'btn_save' => 'บันทึก',
        'title_transfer' => 'โอนสินทรัพย์', 'confirm_transfer' => 'ยืนยันการโอน?', 'lbl_direction' => 'ทิศทาง',
        'opt_spot_to_fut' => 'Spot -> Futures', 'opt_fut_to_spot' => 'Futures -> Spot', 'lbl_transfer_amt' => 'จำนวน', 'ph_amt' => 'จำนวน', 'btn_transfer' => 'โอน',
        'lbl_refreshing' => 'กำลังรีเฟรช...', 'lbl_sec_refresh' => 'วิ', 'lbl_err_occurred' => 'เกิดข้อผิดพลาด',
        'err_comm' => 'ข้อผิดพลาดเครือข่าย', 'err_amt_gt_zero' => 'จำนวนต้อง > 0', 'msg_trans_succ' => 'สำเร็จ', 'msg_trans_fail' => 'ล้มเหลว',
        'err_spot_bal' => 'โหลด Spot ล้มเหลว', 'err_no_usdt_fut' => 'ไม่มีกระเป๋า USDT', 'err_fut_bal' => 'โหลด Futures ล้มเหลว', 'err_pos_fetch' => 'โหลดโพสิชันล้มเหลว', 'err_hist_fetch' => 'โหลดประวัติล้มเหลว',
        'err_no_api_key' => 'ยังไม่ได้ตั้งค่า API', 'err_api_keys_missing' => 'ข้อมูล API ไม่ครบถ้วน', 'err_fut_bal_fail' => 'ข้อผิดพลาดยอด Futures', 'err_spot_bal_fail' => 'ข้อผิดพลาดยอด Spot',
        'mdl_bal_title' => 'ยืนยันการตั้งค่าสินทรัพย์',
        'mdl_bal_cancel' => 'ยกเลิก',
        'mdl_bal_confirm' => 'ยืนยัน',
        'mdl_bal_checking' => 'กำลังตรวจสอบยอดคงเหลือ...',
        'mdl_bal_fut' => 'สินทรัพย์ Futures ตลาดซื้อขาย',
        'mdl_bal_spot' => 'สินทรัพย์ Spot ตลาดซื้อขาย',
        'mdl_bal_set_amt' => 'จำนวนที่ตั้งค่า',
        'mdl_bal_warn_all' => 'จำนวนเงินที่ตั้งไว้สำหรับ futures และ spot มากกว่ายอดคงเหลือจริง',
        'mdl_bal_warn_fut' => 'จำนวนเงินที่ตั้งไว้สำหรับ futures มากกว่ายอดคงเหลือจริง',
        'mdl_bal_warn_spot' => 'จำนวนเงินที่ตั้งไว้สำหรับ spot มากกว่ายอดคงเหลือจริง',
        'mdl_bal_warn_ask' => 'ต้องการดำเนินการต่อด้วยการตั้งค่านี้หรือไม่?',
        'mdl_bal_info' => 'ยอดคงเหลือเพียงพอ ต้องการดำเนินการตั้งค่าหรือไม่?',
        'mdl_bal_err_api' => 'ไม่สามารถตรวจสอบยอดคงเหลือจริง บันทึกด้วยจำนวนเงินที่ป้อนหรือไม่?\nเหตุผล:',
        'mdl_bal_err_comm' => 'เกิดข้อผิดพลาดในการสื่อสาร',
        'mdl_bal_saving' => 'กำลังบันทึก...'
    ],
    'ru' => [
        'login_title' => 'Авторизация', 'login_sub' => 'Пожалуйста, войдите в панель управления.',
        'uid_label' => 'ID пользователя (UID)', 'uid_ph' => 'Введите ваш UID',
        'pwd_label' => 'Пароль', 'pwd_ph' => 'Введите пароль',
        'btn_login' => 'Войти', 'msg_enter_uid_pwd' => 'Пожалуйста, введите UID и пароль.', 'login_fail' => 'Неверный UID или пароль.',
        'cp_title' => 'Смена пароля', 'cp_sub' => 'Пожалуйста, смените пароль для безопасности.',
        'cp_uid' => 'UID', 'cp_exchange' => 'Биржа', 'cp_warn_init' => 'Вы используете начальный пароль. Пожалуйста, смените его.',
        'cp_curr_pwd' => 'Текущий пароль', 'cp_curr_ph' => 'Введите текущий пароль',
        'cp_new_pwd' => 'Новый пароль', 'cp_new_ph' => 'Введите новый пароль',
        'cp_conf_pwd' => 'Подтвердите новый пароль', 'cp_conf_ph' => 'Введите новый пароль еще раз',
        'cp_btn_change' => 'Сменить пароль', 'cp_back_dash' => 'В панель управления',
        'cp_err_empty' => 'Пожалуйста, заполните все поля.', 'cp_err_curr' => 'Текущий пароль неверен.',
        'cp_err_len' => 'Новый пароль должен содержать минимум 4 символа.', 'cp_err_match' => 'Новые пароли не совпадают.', 'cp_err_same' => 'Новый пароль должен отличаться от текущего.',
        'cp_succ' => 'Успешно изменено. Перенаправление...', 'cp_err_fail' => 'Ошибка: ',
        'dash_title' => 'Панель управления', 'dash_chg_pwd' => 'Сменить пароль', 'dash_logout' => 'Выйти',
        'dash_admin_mode' => 'Режим администратора', 'dash_member_list' => 'Список участников',
        'msg_update_ok' => 'Настройки сохранены.', 'msg_txid_ok' => 'TXID сохранен.',
        'msg_trans_ok_amt' => 'Перевод выполнен. Сумма: ', 'msg_trans_fail_rsn' => 'Ошибка перевода: ', 'msg_db_error' => 'Ошибка БД: ',
        'lbl_sym' => 'Пара', 'ph_sym' => 'напр. BTC-USDT', 'btn_search' => 'Поиск',
        'tab_dash' => 'Панель', 'tab_cal' => 'Календарь', 'tab_week' => 'Еженедельно', 'tab_history' => 'История', 'tab_settings_api' => 'Настройки',
        'err_data_load' => 'Ошибка загрузки данных', 'err_data_load_desc' => 'Проверьте настройки API.', 'btn_retry' => 'Повторить', 'btn_debug_log' => 'Отладка',
        'lbl_today_pnl' => 'Прибыль за сегодня', 'lbl_yest_pnl' => 'Прибыль за вчера', 'lbl_30d_pnl' => 'Прибыль за 30 дней', 'lbl_roi_vs' => 'ROI', 'lbl_total_pnl' => 'Общая прибыль',
        'lbl_no_record' => 'Нет записей', 'lbl_total_days_pre' => 'Всего ', 'lbl_total_days_post' => ' дней',
        'title_wallet' => 'Баланс кошелька', 'lbl_fut_wallet' => 'Фьючерсный', 'lbl_base_amt' => 'Базовый капитал', 'lbl_use_avail' => 'Доступно',
        'lbl_spot_wallet' => 'Спотовый', 'lbl_reserve_rate' => 'Ставка резерва', 'lbl_reserve_amt' => 'Сумма резерва',
        'title_curr_pos' => 'Текущие позиции', 'th_symbol' => 'Пара', 'th_position' => 'Позиция', 'th_leverage' => 'Плечо',
        'th_init_qty' => 'Нач кол-во', 'th_entry_qty' => 'Вход кол-во', 'th_martin' => 'Мартин', 'lbl_times' => 'раз',
        'th_entry_px' => 'Цена входа', 'th_curr_px' => 'Тек цена', 'th_liq_px' => 'Цена ликв', 'th_unreal_pnl' => 'Нереализ. PnL',
        'lbl_refresh_5s' => 'Обн 5 сек', 'th_roi' => 'ROI', 'msg_no_pos' => 'Нет открытых позиций.',
        'title_hist_pos' => 'История позиций', 'th_close_time' => 'Время закр', 'th_close_px' => 'Цена закр', 'th_real_pnl' => 'Реализ. PnL',
        'btn_prev' => 'Пред', 'btn_next' => 'След', 'msg_no_hist' => 'Нет истории.',
        'title_cal' => 'Календарь', 'btn_prev_mo' => 'Пред', 'cal_year' => ' ', 'cal_month' => ' ', 'btn_next_mo' => 'След', 'btn_go_today' => 'Сегодня',
        'cal_sun' => 'Вс', 'cal_mon' => 'Пн', 'cal_tue' => 'Вт', 'cal_wed' => 'Ср', 'cal_thu' => 'Чт', 'cal_fri' => 'Пт', 'cal_sat' => 'Сб',
        'cal_mon_tot' => 'Итого за месяц', 'cal_trade_days' => 'Дней торг', 'cal_days' => 'д', 'cal_prof_loss' => 'Приб/Убыт',
        'title_week_roi' => 'Еженедельный ROI', 'title_txid_input' => 'Ввод TXID', 'lbl_select_week' => 'Выбор недели', 'opt_select_week' => 'Выберите...',
        'lbl_input_txid' => 'TXID', 'ph_txid' => 'Введите TXID', 'btn_save_txid' => 'Сохранить',
        'th_week_range' => 'Период', 'th_week_pnl' => 'Приб/нед', 'th_avg_amt' => 'Ср капитал', 'th_week_roi' => 'ROI/нед', 'th_txid' => 'TXID', 'msg_no_data' => 'Нет данных.',
        'title_hist_amt' => 'История переводов', 'th_chg_time' => 'Время', 'th_type' => 'Тип', 'th_amt_before' => 'До', 'th_amt_after' => 'После',
        'badge_spot' => 'Спот', 'badge_fut' => 'Фьюч', 'msg_no_amt_hist' => 'Нет истории.',
        'title_settings' => 'Настройки API', 'lbl_api_key' => 'API Key', 'lbl_sec_key' => 'Secret Key', 'lbl_pwd' => 'Пароль',
        'lbl_reserve_set' => 'Доля перевода', 'lbl_res_0' => '0%', 'lbl_res_30' => '30%', 'lbl_res_100' => '100%', 'lbl_res_desc' => 'Процент прибыли, переводимый на спот',
        'lbl_fut_amt' => 'Капитал фьючерсов', 'lbl_fut_amt_desc' => 'Базовая сумма для бота', 'lbl_spot_amt' => 'Спот капитал',
        'confirm_save' => 'Сохранить изменения?', 'btn_save' => 'Сохранить',
        'title_transfer' => 'Перевод средств', 'confirm_transfer' => 'Выполнить перевод?', 'lbl_direction' => 'Направление',
        'opt_spot_to_fut' => 'Спот -> Фьючерсы', 'opt_fut_to_spot' => 'Фьючерсы -> Спот', 'lbl_transfer_amt' => 'Количество', 'ph_amt' => 'Сумма', 'btn_transfer' => 'Перевод',
        'lbl_refreshing' => 'Обновление...', 'lbl_sec_refresh' => 'с', 'lbl_err_occurred' => 'Ошибка',
        'err_comm' => 'Ошибка связи', 'err_amt_gt_zero' => 'Сумма должна быть > 0.', 'msg_trans_succ' => 'Успешно', 'msg_trans_fail' => 'Ошибка',
        'err_spot_bal' => 'Ошибка баланса Спот', 'err_no_usdt_fut' => 'Нет кошелька USDT', 'err_fut_bal' => 'Ошибка баланса Фьюч', 'err_pos_fetch' => 'Ошибка позиций', 'err_hist_fetch' => 'Ошибка истории',
        'err_no_api_key' => 'API не настроен.', 'err_api_keys_missing' => 'Отсутствуют данные API.', 'err_fut_bal_fail' => 'Ошибка баланса фьючерсов', 'err_spot_bal_fail' => 'Ошибка баланса спот',
        'mdl_bal_title' => 'Подтвердить настройки активов',
        'mdl_bal_cancel' => 'Отмена',
        'mdl_bal_confirm' => 'Подтвердить',
        'mdl_bal_checking' => 'Проверка баланса биржи...',
        'mdl_bal_fut' => 'Фьючерсный актив',
        'mdl_bal_spot' => 'Спотовый актив',
        'mdl_bal_set_amt' => 'Сумма настройки',
        'mdl_bal_warn_all' => 'Введенные суммы для фьючерсов и спота превышают ваш фактический баланс.',
        'mdl_bal_warn_fut' => 'Введенная сумма для фьючерсов превышает ваш фактический баланс.',
        'mdl_bal_warn_spot' => 'Введенная сумма для спота превышает ваш фактический баланс.',
        'mdl_bal_warn_ask' => 'Хотите продолжить с этими настройками?',
        'mdl_bal_info' => 'Достаточный баланс. Хотите применить настройки?',
        'mdl_bal_err_api' => 'Не удалось проверить баланс. Сохранить введенные суммы?\nПричина:',
        'mdl_bal_err_comm' => 'Произошла ошибка связи.',
        'mdl_bal_saving' => 'Сохранение...'
    ],
    'de' => [
        'login_title' => 'Anmelden', 'login_sub' => 'Bitte melden Sie sich an, um zum Dashboard zu gelangen.',
        'uid_label' => 'Benutzer-ID (UID)', 'uid_ph' => 'Geben Sie Ihre UID ein',
        'pwd_label' => 'Passwort', 'pwd_ph' => 'Geben Sie Ihr Passwort ein',
        'btn_login' => 'Anmelden', 'msg_enter_uid_pwd' => 'Bitte UID und Passwort eingeben.', 'login_fail' => 'Ungültige UID oder Passwort.',
        'cp_title' => 'Passwort ändern', 'cp_sub' => 'Bitte ändern Sie Ihr Passwort zur Sicherheit.',
        'cp_uid' => 'UID', 'cp_exchange' => 'Börse', 'cp_warn_init' => 'Sie verwenden das Startpasswort. Bitte ändern Sie es.',
        'cp_curr_pwd' => 'Aktuelles Passwort', 'cp_curr_ph' => 'Aktuelles eingeben',
        'cp_new_pwd' => 'Neues Passwort', 'cp_new_ph' => 'Neues eingeben',
        'cp_conf_pwd' => 'Passwort bestätigen', 'cp_conf_ph' => 'Neues bestätigen',
        'cp_btn_change' => 'Ändern', 'cp_back_dash' => 'Zurück zum Dashboard',
        'cp_err_empty' => 'Bitte füllen Sie alle Felder aus.', 'cp_err_curr' => 'Aktuelles Passwort falsch.',
        'cp_err_len' => 'Das neue Passwort muss mindestens 4 Zeichen lang sein.', 'cp_err_match' => 'Passwörter stimmen nicht überein.', 'cp_err_same' => 'Neues Passwort muss sich unterscheiden.',
        'cp_succ' => 'Erfolgreich geändert. Weiterleitung...', 'cp_err_fail' => 'Fehler: ',
        'dash_title' => 'Dashboard', 'dash_chg_pwd' => 'Passwort ändern', 'dash_logout' => 'Abmelden',
        'dash_admin_mode' => 'Admin-Modus', 'dash_member_list' => 'Mitgliederliste',
        'msg_update_ok' => 'Einstellungen gespeichert.', 'msg_txid_ok' => 'TXID gespeichert.',
        'msg_trans_ok_amt' => 'Transfer erfolgreich. Betrag: ', 'msg_trans_fail_rsn' => 'Transfer fehlgeschlagen: ', 'msg_db_error' => 'DB-Fehler: ',
        'lbl_sym' => 'Paar', 'ph_sym' => 'z.B. BTC-USDT', 'btn_search' => 'Suchen',
        'tab_dash' => 'Dashboard', 'tab_cal' => 'Kalender', 'tab_week' => 'Wöchentlich', 'tab_history' => 'Historie', 'tab_settings_api' => 'Einstellungen',
        'err_data_load' => 'Datenladefehler', 'err_data_load_desc' => 'Bitte überprüfen Sie die API-Einstellungen.', 'btn_retry' => 'Wiederholen', 'btn_debug_log' => 'Debug',
        'lbl_today_pnl' => 'Heute PnL', 'lbl_yest_pnl' => 'Gestern PnL', 'lbl_30d_pnl' => '30T PnL', 'lbl_roi_vs' => 'ROI', 'lbl_total_pnl' => 'Gesamt PnL',
        'lbl_no_record' => 'Keine Aufzeichnung', 'lbl_total_days_pre' => 'Gesamt ', 'lbl_total_days_post' => ' Tage',
        'title_wallet' => 'Wallet-Bestand', 'lbl_fut_wallet' => 'Futures-Wallet', 'lbl_base_amt' => 'Basisbetrag', 'lbl_use_avail' => 'Verfügbar',
        'lbl_spot_wallet' => 'Spot-Wallet', 'lbl_reserve_rate' => 'Reserve-Rate', 'lbl_reserve_amt' => 'Reservebetrag',
        'title_curr_pos' => 'Aktuelle Positionen', 'th_symbol' => 'Paar', 'th_position' => 'Position', 'th_leverage' => 'Hebel',
        'th_init_qty' => 'Startmenge', 'th_entry_qty' => 'Einstiegsmenge', 'th_martin' => 'Martin', 'lbl_times' => 'mal',
        'th_entry_px' => 'Einstiegspreis', 'th_curr_px' => 'Aktueller Preis', 'th_liq_px' => 'Liq. Preis', 'th_unreal_pnl' => 'Unreal. PnL',
        'lbl_refresh_5s' => '5s Refresh', 'th_roi' => 'ROI', 'msg_no_pos' => 'Keine offenen Positionen.',
        'title_hist_pos' => 'Positionsverlauf', 'th_close_time' => 'Schließzeit', 'th_close_px' => 'Schließpreis', 'th_real_pnl' => 'Real. PnL',
        'btn_prev' => 'Zurück', 'btn_next' => 'Weiter', 'msg_no_hist' => 'Kein Verlauf.',
        'title_cal' => 'Kalender', 'btn_prev_mo' => 'Zurück', 'cal_year' => ' ', 'cal_month' => ' ', 'btn_next_mo' => 'Vor', 'btn_go_today' => 'Heute',
        'cal_sun' => 'So', 'cal_mon' => 'Mo', 'cal_tue' => 'Di', 'cal_wed' => 'Mi', 'cal_thu' => 'Do', 'cal_fri' => 'Fr', 'cal_sat' => 'Sa',
        'cal_mon_tot' => 'Monat Total', 'cal_trade_days' => 'Handelstage', 'cal_days' => 'Tage', 'cal_prof_loss' => 'Gewinn/Verlust',
        'title_week_roi' => 'Wöchentlicher ROI', 'title_txid_input' => 'TXID eingeben', 'lbl_select_week' => 'Woche wählen', 'opt_select_week' => 'Wählen...',
        'lbl_input_txid' => 'TXID', 'ph_txid' => 'TXID eingeben', 'btn_save_txid' => 'Speichern',
        'th_week_range' => 'Zeitraum', 'th_week_pnl' => 'Wochen-PnL', 'th_avg_amt' => 'Durchschn. Kapital', 'th_week_roi' => 'Wochen-ROI', 'th_txid' => 'TXID', 'msg_no_data' => 'Keine Daten.',
        'title_hist_amt' => 'Transferverlauf', 'th_chg_time' => 'Zeit', 'th_type' => 'Typ', 'th_amt_before' => 'Vorher', 'th_amt_after' => 'Nachher',
        'badge_spot' => 'Spot', 'badge_fut' => 'Futures', 'msg_no_amt_hist' => 'Kein Verlauf.',
        'title_settings' => 'API-Einstellungen', 'lbl_api_key' => 'API Key', 'lbl_sec_key' => 'Secret Key', 'lbl_pwd' => 'Passwort',
        'lbl_reserve_set' => 'Reserveverhältnis', 'lbl_res_0' => '0%', 'lbl_res_30' => '30%', 'lbl_res_100' => '100%', 'lbl_res_desc' => 'Anteil des Gewinns, der ins Spot-Wallet verschoben wird',
        'lbl_fut_amt' => 'Futures Kapital', 'lbl_fut_amt_desc' => 'Basisbetrag für den Bot', 'lbl_spot_amt' => 'Spot Reserve',
        'confirm_save' => 'Speichern?', 'btn_save' => 'Speichern',
        'title_transfer' => 'Asset Transfer', 'confirm_transfer' => 'Transfer bestätigen?', 'lbl_direction' => 'Richtung',
        'opt_spot_to_fut' => 'Spot -> Futures', 'opt_fut_to_spot' => 'Futures -> Spot', 'lbl_transfer_amt' => 'Menge', 'ph_amt' => 'Menge eingeben', 'btn_transfer' => 'Transfer',
        'lbl_refreshing' => 'Aktualisiere...', 'lbl_sec_refresh' => 's', 'lbl_err_occurred' => 'Fehler',
        'err_comm' => 'Kommunikationsfehler', 'err_amt_gt_zero' => 'Betrag muss > 0 sein.', 'msg_trans_succ' => 'Erfolgreich', 'msg_trans_fail' => 'Fehlgeschlagen',
        'err_spot_bal' => 'Spot-Saldo Fehler', 'err_no_usdt_fut' => 'Kein USDT-Wallet', 'err_fut_bal' => 'Futures-Saldo Fehler', 'err_pos_fetch' => 'Positionsfehler', 'err_hist_fetch' => 'Verlaufsfehler',
        'err_no_api_key' => 'Kein API Key konfiguriert.', 'err_api_keys_missing' => 'API Key fehlt.', 'err_fut_bal_fail' => 'Futures Saldo Fehler', 'err_spot_bal_fail' => 'Spot Saldo Fehler',
        'mdl_bal_title' => 'Asset-Einstellungen bestätigen',
        'mdl_bal_cancel' => 'Abbrechen',
        'mdl_bal_confirm' => 'Bestätigen',
        'mdl_bal_checking' => 'Prüfe Börsenguthaben...',
        'mdl_bal_fut' => 'Futures-Asset der Börse',
        'mdl_bal_spot' => 'Spot-Asset der Börse',
        'mdl_bal_set_amt' => 'Einstellungsbetrag',
        'mdl_bal_warn_all' => 'Die eingegebenen Beträge für Futures und Spot überschreiten Ihr tatsächliches Guthaben.',
        'mdl_bal_warn_fut' => 'Der eingegebene Futures-Betrag überschreitet Ihr tatsächliches Guthaben.',
        'mdl_bal_warn_spot' => 'Der eingegebene Spot-Betrag überschreitet Ihr tatsächliches Guthaben.',
        'mdl_bal_warn_ask' => 'Möchten Sie mit diesen Einstellungen fortfahren?',
        'mdl_bal_info' => 'Ausreichendes Guthaben. Mit den eingegebenen Einstellungen fortfahren?',
        'mdl_bal_err_api' => 'Tatsächliches Guthaben konnte nicht verifiziert werden. Mit eingegebenen Beträgen speichern?\nGrund:',
        'mdl_bal_err_comm' => 'Ein Kommunikationsfehler ist aufgetreten.',
        'mdl_bal_saving' => 'Speichern...'
    ],
    'es' => [
        'login_title' => 'Iniciar sesión', 'login_sub' => 'Inicia sesión para acceder al panel.',
        'uid_label' => 'ID de usuario (UID)', 'uid_ph' => 'Introduce tu UID',
        'pwd_label' => 'Contraseña', 'pwd_ph' => 'Introduce tu contraseña',
        'btn_login' => 'Iniciar sesión', 'msg_enter_uid_pwd' => 'Por favor introduce UID y contraseña.', 'login_fail' => 'UID o contraseña no válidos.',
        'cp_title' => 'Cambiar Contraseña', 'cp_sub' => 'Por favor cambia tu contraseña por seguridad.',
        'cp_uid' => 'UID', 'cp_exchange' => 'Exchange', 'cp_warn_init' => 'Estás usando la contraseña inicial. Por favor cámbiala.',
        'cp_curr_pwd' => 'Contraseña actual', 'cp_curr_ph' => 'Contraseña actual',
        'cp_new_pwd' => 'Nueva Contraseña', 'cp_new_ph' => 'Nueva Contraseña',
        'cp_conf_pwd' => 'Confirmar Contraseña', 'cp_conf_ph' => 'Confirmar Contraseña',
        'cp_btn_change' => 'Cambiar', 'cp_back_dash' => 'Volver al panel',
        'cp_err_empty' => 'Por favor, rellena todos los campos.', 'cp_err_curr' => 'La contraseña actual no coincide.',
        'cp_err_len' => 'La nueva contraseña debe tener al menos 4 caracteres.', 'cp_err_match' => 'Las contraseñas no coinciden.', 'cp_err_same' => 'La nueva contraseña debe ser diferente.',
        'cp_succ' => 'Cambiado con éxito. Redirigiendo...', 'cp_err_fail' => 'Error: ',
        'dash_title' => 'Panel de Control', 'dash_chg_pwd' => 'Cambiar PWD', 'dash_logout' => 'Cerrar sesión',
        'dash_admin_mode' => 'Modo Admin', 'dash_member_list' => 'Lista de miembros',
        'msg_update_ok' => 'Configuración guardada.', 'msg_txid_ok' => 'TXID guardado.',
        'msg_trans_ok_amt' => 'Transferencia completada. Cantidad: ', 'msg_trans_fail_rsn' => 'Error en la transferencia: ', 'msg_db_error' => 'Error en BD: ',
        'lbl_sym' => 'Par', 'ph_sym' => 'ej. BTC-USDT', 'btn_search' => 'Buscar',
        'tab_dash' => 'Panel', 'tab_cal' => 'Calendario', 'tab_week' => 'Semanal', 'tab_history' => 'Historial', 'tab_settings_api' => 'Ajustes',
        'err_data_load' => 'Error de datos', 'err_data_load_desc' => 'Comprueba la configuración de API.', 'btn_retry' => 'Reintentar', 'btn_debug_log' => 'Depurar',
        'lbl_today_pnl' => 'PnL Hoy', 'lbl_yest_pnl' => 'PnL Ayer', 'lbl_30d_pnl' => 'PnL 30 Días', 'lbl_roi_vs' => 'ROI', 'lbl_total_pnl' => 'PnL Total',
        'lbl_no_record' => 'Sin registros', 'lbl_total_days_pre' => 'Total ', 'lbl_total_days_post' => ' días',
        'title_wallet' => 'Activos de Wallet', 'lbl_fut_wallet' => 'Wallet Futuros', 'lbl_base_amt' => 'Capital Base', 'lbl_use_avail' => 'Disponible',
        'lbl_spot_wallet' => 'Wallet Spot', 'lbl_reserve_rate' => 'Tasa de reserva', 'lbl_reserve_amt' => 'Reserva',
        'title_curr_pos' => 'Posiciones Actuales', 'th_symbol' => 'Par', 'th_position' => 'Posición', 'th_leverage' => 'Apalan...',
        'th_init_qty' => 'Cant Inicial', 'th_entry_qty' => 'Cant Entrada', 'th_martin' => 'Martin', 'lbl_times' => 'veces',
        'th_entry_px' => 'Precio Ent', 'th_curr_px' => 'Precio Act', 'th_liq_px' => 'Precio Liq', 'th_unreal_pnl' => 'PnL No Realiz',
        'lbl_refresh_5s' => 'Actuliz. 5s', 'th_roi' => 'ROI', 'msg_no_pos' => 'No hay posiciones.',
        'title_hist_pos' => 'Historial de Posiciones', 'th_close_time' => 'Tiempo Cierre', 'th_close_px' => 'Precio Cierre', 'th_real_pnl' => 'PnL Realiz',
        'btn_prev' => 'Ant', 'btn_next' => 'Sig', 'msg_no_hist' => 'Sin historial.',
        'title_cal' => 'Calendario', 'btn_prev_mo' => 'Ant', 'cal_year' => ' ', 'cal_month' => ' ', 'btn_next_mo' => 'Sig', 'btn_go_today' => 'Hoy',
        'cal_sun' => 'Dom', 'cal_mon' => 'Lun', 'cal_tue' => 'Mar', 'cal_wed' => 'Mié', 'cal_thu' => 'Jue', 'cal_fri' => 'Vie', 'cal_sat' => 'Sáb',
        'cal_mon_tot' => 'Total Mes', 'cal_trade_days' => 'Días Op.', 'cal_days' => 'días', 'cal_prof_loss' => 'Ganan/Pérd',
        'title_week_roi' => 'ROI Semanal', 'title_txid_input' => 'Ingresar TXID', 'lbl_select_week' => 'Seleccionar Sem', 'opt_select_week' => 'Seleccionar...',
        'lbl_input_txid' => 'TXID', 'ph_txid' => 'Introduce TXID', 'btn_save_txid' => 'Guardar',
        'th_week_range' => 'Período', 'th_week_pnl' => 'PnL Semanal', 'th_avg_amt' => 'Capital Prom', 'th_week_roi' => 'ROI Semanal', 'th_txid' => 'TXID', 'msg_no_data' => 'No hay datos.',
        'title_hist_amt' => 'Historial de Trasferencias', 'th_chg_time' => 'Hora', 'th_type' => 'Tipo', 'th_amt_before' => 'Antes', 'th_amt_after' => 'Después',
        'badge_spot' => 'Spot', 'badge_fut' => 'Futuros', 'msg_no_amt_hist' => 'Sin historial.',
        'title_settings' => 'Ajustes API', 'lbl_api_key' => 'API Key', 'lbl_sec_key' => 'Secret Key', 'lbl_pwd' => 'Contraseña',
        'lbl_reserve_set' => 'Ratio de reserva', 'lbl_res_0' => '0%', 'lbl_res_30' => '30%', 'lbl_res_100' => '100%', 'lbl_res_desc' => 'Porcentaje de ganancias a transferir a Spot',
        'lbl_fut_amt' => 'Capital de Futuros', 'lbl_fut_amt_desc' => 'Monto base del bot', 'lbl_spot_amt' => 'Capital Spot',
        'confirm_save' => '¿Guardar cambios?', 'btn_save' => 'Guardar',
        'title_transfer' => 'Transferir Activos', 'confirm_transfer' => '¿Proceder?', 'lbl_direction' => 'Dirección',
        'opt_spot_to_fut' => 'Spot -> Futuros', 'opt_fut_to_spot' => 'Futuros -> Spot', 'lbl_transfer_amt' => 'Cantidad', 'ph_amt' => 'Cantidad', 'btn_transfer' => 'Transferir',
        'lbl_refreshing' => 'Actualizando...', 'lbl_sec_refresh' => 's', 'lbl_err_occurred' => 'Error',
        'err_comm' => 'Error de red', 'err_amt_gt_zero' => 'La cantidad debe ser > 0.', 'msg_trans_succ' => 'Éxito', 'msg_trans_fail' => 'Fallo',
        'err_spot_bal' => 'Error en saldo Spot', 'err_no_usdt_fut' => 'No hay wallet USDT', 'err_fut_bal' => 'Error en saldo Futuros', 'err_pos_fetch' => 'Error en posiciones', 'err_hist_fetch' => 'Error en historial',
        'err_no_api_key' => 'API no configurada.', 'err_api_keys_missing' => 'Falta info API.', 'err_fut_bal_fail' => 'Error saldo Futuros', 'err_spot_bal_fail' => 'Error saldo Spot',
        'mdl_bal_title' => 'Confirmar Ajustes de Activos',
        'mdl_bal_cancel' => 'Cancelar',
        'mdl_bal_confirm' => 'Confirmar',
        'mdl_bal_checking' => 'Comprobando saldo del exchange...',
        'mdl_bal_fut' => 'Activo Futuros Exchange',
        'mdl_bal_spot' => 'Activo Spot Exchange',
        'mdl_bal_set_amt' => 'Monto Ajustado',
        'mdl_bal_warn_all' => 'Los montos configurados para futuros y spot superan su saldo real.',
        'mdl_bal_warn_fut' => 'El monto de futuros supera su saldo real.',
        'mdl_bal_warn_spot' => 'El monto de spot supera su saldo real.',
        'mdl_bal_warn_ask' => '¿Desea continuar con esta configuración?',
        'mdl_bal_info' => 'Saldo suficiente. ¿Continuar con lo ingresado?',
        'mdl_bal_err_api' => 'No se pudo verificar el saldo real. ¿Guardar con montos ingresados?\nRazón:',
        'mdl_bal_err_comm' => 'Ocurrió un error de comunicación.',
        'mdl_bal_saving' => 'Guardando...'
    ]
];

/**
 * 키에 해당하는 언어 문자열 반환
 */
function t($key) {
    global $lang_data, $current_lang;
    
    // 선택된 언어에 키가 있으면 반환
    if (isset($lang_data[$current_lang][$key])) {
        return $lang_data[$current_lang][$key];
    }
    
    // 없으면 영어로 폴백
    if (isset($lang_data['en'][$key])) {
        return $lang_data['en'][$key];
    }
    
    // 영어에도 없으면 키 자체를 반환
    return $key;
}

/**
 * 언어 선택 UI 컴포넌트 렌더링
 */
function render_language_selector() {
    global $current_lang, $supported_langs;
    
    $flags = [
        'en' => '🇺🇸', 'ko' => '🇰🇷', 'ja' => '🇯🇵', 'zh' => '🇨🇳', 'mn' => '🇲🇳',
        'vi' => '🇻🇳', 'th' => '🇹🇭', 'ru' => '🇷🇺', 'de' => '🇩🇪', 'es' => '🇪🇸'
    ];
    
    $html = '<select onchange="window.location.href=\'?lang=\'+this.value" style="padding: 6px 12px; border-radius: 8px; background: rgba(255, 255, 255, 0.15); border: 1px solid rgba(255,255,255,0.2); color: #fff; cursor: pointer; font-weight: 500; font-size: 0.9rem; appearance: none; outline: none;">';
    
    foreach($supported_langs as $l) {
        $sel = ($current_lang === $l) ? 'selected' : '';
        $html .= "<option value=\"{$l}\" {$sel} style=\"color:#333;\">{$flags[$l]} " . strtoupper($l) . "</option>";
    }
    
    $html .= '</select>';
    return $html;
}
?>